from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtGui import QFont


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(957, 598)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.calendarWidget = QtWidgets.QCalendarWidget(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Maximum, QtWidgets.QSizePolicy.Policy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.calendarWidget.sizePolicy().hasHeightForWidth())
        self.calendarWidget.setSizePolicy(sizePolicy)
        self.calendarWidget.setMinimumSize(QtCore.QSize(100, 100))
        self.calendarWidget.setStyleSheet("font: 75 8pt \"MS Shell Dlg 2\";")
        self.calendarWidget.setObjectName("calendarWidget")
        self.gridLayout.addWidget(self.calendarWidget, 0, 0, 2, 1)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.changeButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.changeButton.setObjectName("changeButton")
        self.gridLayout_2.addWidget(self.changeButton, 1, 0, 1, 1)
        self.newButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.newButton.setObjectName("saveButton")
        self.gridLayout_2.addWidget(self.newButton, 0, 0, 1, 1)
        self.delete_completed_Button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.delete_completed_Button.setObjectName("delete_completed_Button")
        self.gridLayout_2.addWidget(self.delete_completed_Button, 3, 0, 1, 1)
        self.all_Button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.all_Button.setObjectName("nearest_Button")
        self.gridLayout_2.addWidget(self.all_Button, 0, 1, 1, 1)
        self.saerch_Button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.saerch_Button.setObjectName("showButton")
        self.gridLayout_2.addWidget(self.saerch_Button, 1, 1, 1, 1)
        self.deleteButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.deleteButton.setObjectName("deleteButton")
        self.gridLayout_2.addWidget(self.deleteButton, 3, 1, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_2, 0, 1, 1, 1)
        self.dataTable = QtWidgets.QTableWidget(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding,
                                           QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dataTable.sizePolicy().hasHeightForWidth())
        self.dataTable.setSizePolicy(sizePolicy)
        self.dataTable.setBaseSize(QtCore.QSize(0, 0))
        self.dataTable.setObjectName("dataTable")
        self.gridLayout.addWidget(self.dataTable, 2, 0, 2, 2)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.count_active = QtWidgets.QLabel(parent=self.centralwidget)
        self.count_active.setObjectName("count_active")
        self.gridLayout_3.addWidget(self.count_active, 0, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout_3.addWidget(self.label_3, 2, 0, 1, 1)
        self.count_nonactive = QtWidgets.QLabel(parent=self.centralwidget)
        self.count_nonactive.setObjectName("count_nonactive")
        self.gridLayout_3.addWidget(self.count_nonactive, 2, 1, 1, 1)
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setObjectName("label")
        self.gridLayout_3.addWidget(self.label, 0, 0, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_3, 1, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 957, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Планировщик задач"))
        self.changeButton.setText(_translate("MainWindow", "Изменить"))
        self.newButton.setText(_translate("MainWindow", "Создать"))
        self.delete_completed_Button.setText(_translate("MainWindow", "Удалить выполненные"))
        self.all_Button.setText(_translate("MainWindow", "Все задачи"))
        self.saerch_Button.setText(_translate("MainWindow", "Поиск"))
        self.deleteButton.setText(_translate("MainWindow", "Удалить"))
        self.count_active.setText(_translate("MainWindow", "0"))
        self.label_3.setText(_translate("MainWindow",
                                        "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt; font-weight:600;\">Количество выполненных задач</span></p></body></html>"))
        self.count_nonactive.setText(_translate("MainWindow", "0"))
        self.label.setText(_translate("MainWindow",
                                      "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt; font-weight:600;\">Количесвто автивных задач</span></p></body></html>"))
        font = QFont("Arial", 10)
        self.dataTable.setFont(font)
        self.newButton.setFont(QFont("Arial", 12, QFont.Weight.Bold))
        self.saerch_Button.setFont(QFont("Arial", 12, QFont.Weight.Bold))
        self.all_Button.setFont(QFont("Arial", 12, QFont.Weight.Bold))
        self.deleteButton.setFont(QFont("Arial", 12, QFont.Weight.Bold))
        self.delete_completed_Button.setFont(QFont("Arial", 12, QFont.Weight.Bold))
        self.count_active.setFont(QFont("Arial", 12, QFont.Weight.Bold))
        self.count_nonactive.setFont(QFont("Arial", 12, QFont.Weight.Bold))
        self.changeButton.setFont(QFont("Arial", 12, QFont.Weight.Bold))
